soap-service:
  country:
    packages: com.example.country.client.gen
    endpoint: http://localhost:8090/websamples.countryinfo/CountryInfoService.wso?WSDL
  number:
    packages: com.example.number.client.gen
    endpoint: http://localhost:8090/webservicesserver/numberconversion.wso?WSDL

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    root: "info"
    org.springframework.web: "debug"